#
# sortin-hat
# K8s Deployment
# GKE Kustomization
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base
secretGenerator:
  - behavior: merge
    name: ml-pipeline-postgresql
    env: secrets/.postgres.env
  - behavior: merge
    name: ml-pipeline-airflow-metadata
    env: secrets/.airflow.env
commonLabels:
  app.kubernetes.io/part-of: sortin-hat
  app.kubernetes.io/component: ml-pipeline
  app.kubernetes.io/managed-by: kustomize
