#
# sortin-hat
# K8s Deployment
# GKE Kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base
secretGenerator:
  - behavior: replace
    name: airflow-postgresql
    env: secrets/.postgres.env
