#
# sortin-hat
# K8s Deployment
# Kustomize Base
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  # Postgres - Shared Database for Airflow & MLFlow
  - repo: https://charts.bitnami.com/bitnami
    name: postgresql
    releaseName: ml-pipeline
    valuesInline:
      primary:
        # initdb: create database for Airflow deployment
        initdb:
            scripts:
              create_db.sql: |
                CREATE DATABASE airflow;
  # Airflow - Workflow Orchestration
  - repo: https://airflow.apache.org
    name: airflow
    version: 1.6.0
    releaseName: ml-pipeline
    valuesInline:
      executor: KubernetesExecutor
      # use postgresql database deployed separately via db connection string
      # in '<RELEASE>-airflow-metadata' secret
      postgresql:
        enabled: false
