#
# sortin-hat
# K8s Deployment
# Kustomize Base
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  # Postgres - Shared Database for Airflow & MLFlow
  - repo: https://charts.bitnami.com/bitnami
    name: postgresql
    releaseName: "db"
  # Airflow - Workflow Orchestration
  - repo: https://airflow.apache.org
    name: airflow
    version: 1.6.0
    releaseName: airflow
    valuesInline:
      executor: KubernetesExecutor
      # depend onpostgresql database deployed separately using db connection
      # string in '<RELEASE>-airflow-metadata' secret
      postgresql:
        enabled: false
