#
# sortin-hat
# Test Pipeline
#

name: "Test Sortin-hat Pipeline"
on:
  push: {}
jobs:
  test:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_key.json
    strategy:
      fail-fast: true
      matrix:
        kind: [unit, integration]
    name: "${{ matrix.kind }} Test Sortin-hat Pipeline"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        # cache pip modules between workflow runs
        cache: 'pip'
    - name: "Install development Pip modules"
      run:
        pip install -r pipeline/requirements-dev.txt
    - name: "Decode & Write GCP Key"
      run: >
        printf '${{ secrets.GCP_PIPELINE_SERVICE_ACCOUNT_KEY_B64 }}' |
          base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
    - name: "Write GCP Key & Template dotenv file"
      run: |
        sed -e "
          s/POSTGRES_PASSWORD=/POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}/;
          s|GOOGLE_APPLICATION_CREDENTIALS=|GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS|;
        " env >.env
    - name: "Run ${{ matrix.kind }} tests"
      env:
        # increase test containers max tries to give more time for compose deployment
        # to boot up during integration test.
        TC_MAX_TRIES: 600
      working-directory: pipeline
      run: pytest -m ${{ matrix.kind }}
